* fix environment set with a double quoted string

diff --git a/mudo b/mudo
--- a/mudo
+++ b/mudo
@@ -17,7 +17,7 @@ usage:
    mudo [-e|-f] <command> ...
 
    mudo lets you execute commands with an unrestricted PATH from within a
-   mulle-env environment.
+   mulle-env environment. It does not let you break out of a sandbox though.
    With the -e option you can replace the current environment with the
    unrestricted user environment.
    With the -f option you can run mudo even if there is no current environment
@@ -96,7 +96,7 @@ filename="${MULLE_ENV_VAR_DIR}/old-environment"
 environment="`cat "${filename}" 2> /dev/null`"
 if [ -z "${environment}" ]
 then
-   echo "error: mudo did not find previous environment (${filename})" >&2
+   echo "error: mudo did not find a previous environment (${filename})" >&2
    exit 1
 fi
 
