* you can now use --concat and --concat0 for environment set installer now accepts libexecname some bug fixes

diff --git a/mudo b/mudo
--- a/mudo
+++ b/mudo
@@ -76,7 +76,21 @@ fi
 #    MULLE_ENV_ETC_DIR='/Volumes/Source/srcM/mulle-cpp/.mulle/etc/env'
 #    MULLE_ENV_SHARE_DIR='/Volumes/Source/srcM/mulle-cpp/.mulle/share/env'
 #
-eval "`mulle-env --search-as-is mulle-tool-env env`" || exit 1
+# If this doesn't work we are in a "none" environment, presumably
+if ! MULLE_ENV="${MULLE_ENV:-"`command -v mulle-env`"}"
+then
+   echo "error: mulle-env not in PATH ($PATH)
+Tip: mudo can not be used from a \"none\" environment." >&2
+   exit 1
+fi
+
+eval "`"${MULLE_ENV}" --search-as-is mulle-tool-env env`"
+
+if [ -z "${MULLE_ENV_VAR_DIR}" ]
+then
+   echo "error: mulle-env failed to provide MULLE_ENV_VAR_DIR" >&2
+   exit 1
+fi
 
 filename="${MULLE_ENV_VAR_DIR}/old-environment"
 environment="`cat "${filename}" 2> /dev/null`"
@@ -89,13 +103,19 @@ fi
 #
 # does not work with builtins like `command -v ps`
 #
-
-set -- exec env -i - "${environment}" "$@"
+OLDIFS="${IFS}"
+IFS="
+"
+for line in ${environment}
+do
+   set -- "${line}" "$@"
+done
+IFS="${OLDIFS}"
 
 if [ -z "${MULLE_OLDPATH}" ]
 then
-   "$@"
+   exec env -i - "$@"
 else
-   PATH="${MULLE_OLDPATH}" "$@"
+   PATH="${MULLE_OLDPATH}" exec env -i - "$@"
 fi
 
diff --git a/test/10-tool2/run-test b/test/10-tool2/run-test
--- a/test/10-tool2/run-test
+++ b/test/10-tool2/run-test
@@ -32,17 +32,19 @@ main()
    r_make_tmp_directory || exit 1
    directory="${RVAL:-/tmp/exekutor}"
 
-   cd "${directory}" || exit 1
+   exekutor cd "${directory}" || exit 1
 
-   run_mulle_env -s init --style none/tight
+   run_mulle_env -s init --style minimal/tight
+   run_mulle_env -ld -lx tool compile
+   run_mulle_env -ld -lx tool link
 
-   value="`run_mulle_env -s tool list --no-color | grep -E '^mudo$'`"
-   [ "${value}" != 'mudo' ] && fail "#1: not mudo is wrong here"
+   value="`run_mulle_env -s tool list --no-color | grep -E '^mudo;'`"
+   [ "${value}" != 'mudo;required' ] && fail "#1: not mudo;required is wrong here ($value)"
 
    log_verbose "----- #1 PASSED -----"
 
    value="`run_mulle_env -s tool get mudo`"
-   [ "${value}" != 'mudo' ] && fail "#2: no mudo after get is wrong"
+   [ "${value}" != 'mudo' ] && fail "#2: no mudo after get is wrong ($value)"
 
    log_verbose "----- #2 PASSED -----"
 
@@ -66,19 +68,19 @@ main()
 
    log_verbose "----- #4 PASSED -----"
 
-   if ! run_mulle_env tool --os foobar add ls
+   if ! run_mulle_env tool --os foobar add grep
    then
       fail "#5: Unexpected add failure"
    fi
 
    value="`run_mulle_env -s tool list --no-color os`"
-   [ "${value}" = "foobar"  ] && fail "#5: foobar not known"
+   [ "${value}" = "foobar"  ] && fail "#5: foobar not known ($value)"
 
-   value="`run_mulle_env -s tool get ls`"
-   [ ! -z "${value}"  ] && fail "#5: ls only available in foobar"
+   value="`run_mulle_env -s tool get grep`"
+   [ ! -z "${value}"  ] && fail "#5: grep only available in foobar ($value)"
 
-   value="`run_mulle_env -s tool --os foobar get ls`"
-   [ "${value}" != "ls" ] && fail "#5: ls not available in foobar"
+   value="`run_mulle_env -s tool --os foobar get grep`"
+   [ "${value}" != "grep" ] && fail "#5: grep not available in foobar ($value)"
 
    run_mulle_env -s tool compile
 
@@ -86,12 +88,49 @@ main()
 
    result="`cat "${vardir}/tool"`"
    expect="awk
-mudo"
-   [ "${expect}" != "${result}" ] && fail "#5: result ${result} did not match ${expect}"
+bash
+cat;required
+chgrp;required
+chmod;required
+chown;required
+cp;required
+date;required
+dd
+df
+dmesg
+echo;required
+false;required
+hostname
+kill;required
+ln;required
+login
+ls;required
+mkdir;required
+mknod
+more;required
+mount
+mudo;required
+mv;required
+ps
+pwd;required
+readlink;required
+rmdir;required
+rm;required
+sed;required
+sh;required
+stty
+su
+sync
+true;required
+tty
+umount
+uname;required
+zsh"
+   [ "${expect}" != "${result}" ] && fail "#5: result \"${result}\" did not match \"${expect}\""
 
    log_verbose "----- #5 PASSED -----"
 
-   [ -x "${vardir}/bin/ls" ] && fail "#6: ls already in bin"
+   [ -x "${vardir}/bin/grep" ] && fail "#6: grep already in bin"
 
    if ! run_mulle_env -s tool link
    then
@@ -99,13 +138,13 @@ mudo"
    fi
 
    [ ! -x "${vardir}/bin/awk" ] && fail "#6: awk not in bin"
-   [ -x "${vardir}/bin/ls" ] && fail "#6: ls in bin, but should not be"
+   [ -x "${vardir}/bin/grep" ] && fail "#6: grep in bin, but should not be"
 
    log_verbose "----- #7 PASSED -----"
 
    if [ -z "`command -v ishouldnotexist`" ]
    then
-      if ! run_mulle_env tool --current add ishouldnotexist
+      if ! run_mulle_env tool --current add --required ishouldnotexist
       then
          fail "#7: Unexpected add failure"
       fi
