prerelease

diff --git a/mulle-env b/mulle-env
--- a/mulle-env
+++ b/mulle-env
@@ -291,8 +291,8 @@ env::setup_environment()
       # usefule for related directories, that are placed outside of the
       # project like maybe KITCHEN_DIR
       #
-      MULLE_VIRTUAL_ROOT_ID="$(PATH='/bin:/usr/bin:/usr/local/bin' shasum -a 256 <<< "${MULLE_VIRTUAL_ROOT}")"
-      MULLE_VIRTUAL_ROOT_ID="${MULLE_VIRTUAL_ROOT_ID:1:12}"
+      r_fnv1a_32  "${MULLE_VIRTUAL_ROOT}"
+      printf -v MULLE_VIRTUAL_ROOT_ID "%08x" "${RVAL}"
 
       log_fluff "mulle-env sets MULLE_VIRTUAL_ROOT to \"${MULLE_VIRTUAL_ROOT}\" ($MULLE_VIRTUAL_ROOT_ID)"
    fi
@@ -429,7 +429,7 @@ function env::exekutor_no_stderr()
 # returns 0 : locked successfully
 # return  1 : locked successfully after a timeout
 # return  2 : failed to lock
-# return  3 : lock considered stale
+# return  3 : stale lock overridden
 #
 env::lock_existing_directory()
 {
@@ -452,40 +452,67 @@ env::lock_existing_directory()
 
    log_verbose "$$ waiting for other process to release \"${lockdir}\""
 
-   local start_time
    local current_time
    local elapsed
-
-   start_time=$(date +%s)
-
+   local stale_seconds='15'
+   local wait_seconds
    local creation_time
+   local stale_lockdir
+   local age
 
    while :
    do
-      creation_time="`modification_timestamp "${lockdir}" `"
-
-      elapsed=$((start_time - creation_time))
-      if [ $elapsed -ge 60 ]
-      then
-         log_verbose "$$ found stale \"${lockdir}\" `ls -la $(dirname -- "${lockdir}")`"
-         return 3
-      fi
-
-      sleep 0.025
-
       if env::exekutor_no_stderr mkdir "${lockdir}"
       then
          log_verbose "$$ created \"${lockdir}\""
          return 1
       fi
 
+      creation_time="`modification_timestamp "${lockdir}" `"
+      [ -z "${creation_time}" ] && creation_time="$(date +%s)"
+
       current_time=$(date +%s)
-      elapsed=$((current_time - start_time))
-      if [ $elapsed -ge 30 ]
+      elapsed=$((current_time - creation_time))
+      if [ ${elapsed} -lt ${stale_seconds} ]
       then
-         log_warning "$$ failed to acquire \"${lockdir}\" `ls -la $(dirname -- "${lockdir}")`"
-         return 2
+         wait_seconds=$((stale_seconds - elapsed))
+         [ ${wait_seconds} -lt 1 ] && wait_seconds=1
+         log_info "$$ waiting ${wait_seconds}s for contested lock \"${lockdir}\""
+         sleep "${wait_seconds}"
+         continue
       fi
+
+      stale_lockdir="${lockdir}.stale.${BASHPID:-$$}.${current_time}"
+
+      if ! env::exekutor_no_stderr mv "${lockdir}" "${stale_lockdir}"
+      then
+         sleep 0.025
+         continue
+      fi
+
+      if ! env::exekutor_no_stderr mkdir "${lockdir}"
+      then
+         env::exekutor_no_stderr rmdir "${stale_lockdir}" || :
+         sleep 0.025
+         continue
+      fi
+
+      creation_time="`modification_timestamp "${stale_lockdir}" `"
+      [ -z "${creation_time}" ] && creation_time="${current_time}"
+      current_time=$(date +%s)
+      age=$((current_time - creation_time))
+      env::exekutor_no_stderr rmdir "${stale_lockdir}" || :
+      if [ ${age} -ge ${stale_seconds} ]
+      then
+         log_warning "$$ detected stale lock \"${lockdir}\" (${age}s old) and broke it"
+         return 3
+      fi
+
+      wait_seconds=$((stale_seconds - age))
+      [ ${wait_seconds} -lt 1 ] && wait_seconds=1
+      log_warning "$$ contested lock \"${lockdir}\" was younger than ${stale_seconds}s (${age}s), waiting ${wait_seconds}s before retry"
+      env::exekutor_no_stderr rmdir "${lockdir}" || :
+      sleep "${wait_seconds}"
    done
 }
 
@@ -501,9 +528,9 @@ env::unlock_existing_directory()
    env::r_lock_dir "${directory}"
    lockdir="${RVAL}"
 
-   [ -d "${lockdir}" ] || log_warning "Directory \"${lockdir}\" should exist"
+   [ -d "${lockdir}" ] || return 0
 
-   env::exekutor_no_stderr rmdir "${lockdir}" || log_error "Could not remove \"${lockdir}\" not good"
+   env::exekutor_no_stderr rmdir "${lockdir}" || log_warning "Could not remove \"${lockdir}\""
    log_debug "$$ removed \"${lockdir}\""
 }
 
@@ -850,12 +877,12 @@ check your tool list.
    exekutor mkdir -p "${vardir}"
    env::lock_existing_directory "${vardir}"
    case $? in
-      0|2|3)
+      0|3)
       ;;
 
-      1)
-         # if we a locked after a timeout, assume another process set it
-         # up already, so don't do it again
+      1|2)
+         # if we locked after a timeout, or couldn't lock in time, assume
+         # another process is setting this up and don't mutate concurrently
          return
       ;;
    esac
@@ -864,12 +891,12 @@ check your tool list.
 
    env::lock_existing_directory "${MULLE_ENV_VAR_DIR}"
    case $? in
-      0|2|3)
+      0|3)
       ;;
 
-      1)
-         # if we a locked after a timeout, assume another process set it
-         # up already, so don't do it again
+      1|2)
+         # if we locked after a timeout, or couldn't lock in time, assume
+         # another process is setting this up and don't mutate concurrently
          env::unlock_existing_directory "${vardir}"
          return
       ;;
@@ -1602,6 +1629,7 @@ MULLE_ENVIRONMENT_RELAX_KEYS="\
 DBUS_SESSION_BUS_ADDRESS
 DISPLAY \
 EDITOR \
+GIT_CONFIG_GLOBAL \
 HOME \
 LOGNAME \
 LS_COLORS \
