* some fixes for different style with / instead of :

diff --git a/src/mulle-env-shell b/src/mulle-env-shell
--- a/src/mulle-env-shell
+++ b/src/mulle-env-shell
@@ -53,7 +53,7 @@ emit_initfile()
    fi
    if [ ! -f "${envfile}" ]
    then
-      echo "\"${ENVFILENAME}\" not found, can not continue" >&2
+      echo "\"${envfile}\" not found, can not continue" >&2
       exit 1
    fi
 
